[project]
name = "movieedit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ffmpeg-python>=0.2.0",

    "imageio-ffmpeg>=0.6.0",

    "moviepy>=2.2.1",
    "pytube>=15.0.0",
    "pytubefix>=9.4.1",
]
